# Generated by Django 2.2.7 on 2019-11-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('dt_criacao', models.DateField(auto_now_add=True)),
                ('dt_publicacao', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Publicado', 'Publicado')], max_length=15)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postagem.Autor')),
            ],
        ),
    ]
