# Generated by Django 2.2.7 on 2019-12-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='slug',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autor.Autor'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
