# Generated by Django 2.2.7 on 2019-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='', max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('ocupacao', models.CharField(blank=True, max_length=80, null=True)),
                ('resumo_perfil', models.TextField()),
            ],
        ),
    ]
