# Generated by Django 2.2.7 on 2019-12-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_auto_20191129_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='ocupacao_2',
        ),
    ]
